- .eslintrc.cjs
- README.md
- src/App.tsx
Fixed eslintrc bug and changed README.md
> [fixbug]: changed readme and eslintrc

- .husky/pre-commit
Unnecessary part of the code removed.
> [fix]: change .husky/pre-commit file

- src/api/api.ts
- src/main.tsx
- src/pages/PhonesPage.tsx
- src/store/productsSlice.ts
- src/store/store.ts
- src/types/Product.ts
added basic redux functionality, product types, loading products from json. 
how it looks: https://snipboard.io/kYiVUd.jpg
> [UI] load products from json

- src/App.tsx
- src/components/Favourites/FavouriteItem.tsx
- src/components/Favourites/FavouritesPage.tsx
Description:
create page Favourites
installing the current Cart page in the router
> [86bybjpw5]create favourites page

- src/components/Footer/Footer.tsx
> fixed adaptive footer

- src/components/CardItem/CardItem.tsx
- src/components/Category/Category.tsx
- src/components/Favourites/FavouriteItem.tsx
- src/components/Favourites/FavouritesPage.tsx
- src/hooks/useFavouriteProducts.ts
- src/store/favouriteSlice.ts
Description:
creating a hook that adds and removes products from favorites
> [86bydy0pg]creating fav-products hook

- src/components/CardItem/CardItem.tsx
- src/components/Category/CategoryItem.tsx
- src/components/Favourites/FavouriteItem.tsx
- src/hooks/useFavouriteProducts.ts
- src/store/favouriteSlice.ts
Description:
creating logic for deleting a product from favourites
> [86bybjpy5]creating logic for deleting a product from favourites

- src/components/About.tsx
Add section about.
But now it will not work until not added alse content on that page
> Add section about

- package-lock.json
- package.json
- src/components/SwiperForModels/SwiperForModels.tsx
- src/pages/HomePage.tsx
Add slider for model without adaptive
> add slider for model without adaptive

- src/components/About.tsx
Made it adaptive for tablets and phones
> Add adaptive version for about and tech specs

- src/components/SwiperForModels/SwiperForModels.tsx
add adaptive and style for buttons
> add adaptive and style for buttons

- src/components/PhoneOptionsSelector/PhoneOptionsSelector.tsx
- src/types/enums.ts
Description:
Create variants/acions block
> [86bybjpw0]create phone-options-selector

- src/components/Layout.tsx
- src/components/PromoSlider/SliderPromo.module.css
- src/components/PromoSlider/SliderPromo.tsx
- tailwind.config.js
Added promo slider that adapts to different screens.
> [TaskID 86bye9yg9]: Add promo slider adaptive

- src/components/PhoneOptionsSelector/PhoneOptionsSelector.tsx
- src/components/ProductDetails/ProductDetails.tsx
Description: 
add-block-option-selector-to-block-phonedetails
> [86bybjq2h]add-block-option-selector-to-block-phonedetails

- src/ToastContainer.tsx
- src/components/Layout.tsx
- src/store/cartSlice.ts
> Add message when smth adding or deleting

- src/components/SortComponent/SortComponent.tsx
- src/components/SortComponent/SortDropdown.tsx
- src/pages/PhonesPage.tsx
Add new component for costomised sort dropdown
> add new component for costomised sort dropdown

- src/pages/ProductList.tsx
transferred  phone page to productList
> transferred  phone page to productList

- src/components/Header/Header.tsx
- src/components/Header/Navigation.tsx
> fixed style for burger menu

- src/components/ProductDetails/ProductDetails.tsx
Description:
add props in SliderModels
> add props in SliderModels

- src/components/HomeTitle/HomeTitle.tsx
- src/components/ProductDetails/ProductDetails.tsx
- src/components/SliderModels/SliderModels.tsx
- src/pages/HomePage.tsx
Description:
fixing the title style
refactoring a code
> fixing title

- src/ToastContainer.tsx
- src/components/CardItem/CardItem.tsx
- src/components/ColorTheme/ColorTheme.css
- src/components/Footer/Footer.tsx
- src/components/Layout.tsx
- src/hooks/useColorTheme.ts
- tailwind.config.js
added basic button for swapping themes, fixed some colors
> added basic button for swapping themes, fixed some colors

- src/components/About.tsx
- src/components/CardItem/CardItem.tsx
- src/components/Cart/CartPage.tsx
- src/components/Cart/components/CartItem.tsx
- src/components/Cart/components/Checkout.tsx
- src/components/Category/Category.tsx
- src/components/Favourites/FavouriteItem.tsx
- src/components/ProductDetails/ProductDetails.tsx
- src/components/SelectedProductFilter/SelectedProductFilter.tsx
- src/components/SliderModels/SliderModels.tsx
- src/components/SliderPromo/SliderPromo.tsx
- src/components/SortComponent/SortComponent.tsx
- src/components/SubTitle/SubTitle.tsx
- src/components/Title/Title.tsx
- src/pages/HomePage.tsx
- src/pages/ProductList.tsx
- src/utils/animations.ts
Description:
creating-animation
refactoring
> creating-animation-step-2

- src/components/Reg/Log/Login.tsx
- src/components/Reg/Log/Register.tsx
> add register and login form

- src/components/Cart/components/Checkout.tsx
- src/components/Footer/Footer.tsx
- src/components/Header/Header.tsx
- src/components/Modal/MyModal.module.css
> fix footer bug

- src/components/SortComponent/SortComponent.tsx
- src/pages/ProductList.tsx
- src/store/perPageSlice.ts
> fix bug with URL perPage

- src/components/ColorTheme/ColorTheme.css
- src/components/SortComponent/SortDropdown.tsx
> dark style for sort select

- src/components/ColorTheme/ColorTheme.css
- src/components/SliderModels/SliderModels.tsx
- tailwind.config.js
> fix style for slider buttons

- src/App.tsx
- src/components/CardItem/CardItem.tsx
- src/components/ProductDetails/ProductDetails.tsx
- src/pages/CategoryValidator.tsx
- src/pages/NotFoundPage.tsx
> fix: not found page
